title: Yemi Laja
description: Performing Artist · Transformational Coach · Creative Director
url: "https://yemilaja.co.uk"
baseurl: "/yemi-jekyll"

# Build
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
